company = input()
address = input()
phone = input()
fax = input()
site = input()
first_name = input()
last_name = input()
age = input()
local_phone = input()

print(company)
print(f"Address: {address}")
print(f"Tel. {phone}")
print(f"Fax: ")
print(f"Web site: {site}")
print(f"Manager: {first_name} {last_name} (age: {age}, tel. {local_phone})")